<?php

namespace Wibellule\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends EntityRepository
{
    public function getArticlesPaginate($nbPerPage, $page)
    {
        if ($page < 1) {
            throw new \InvalidArgumentException("L'argument $page ne peut être inférieur à 1");
        }

        $query = $this->createQueryBuilder('q')
            ->orderBy('q.date', 'DESC')
            ->getQuery();

        $query->setFirstResult(($page - 1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query);
    }
}
